# Use phusion/baseimage as base image. To make your builds
# reproducible, make sure you lock down to a specific version, not
# to `latest`! See
# https://github.com/phusion/baseimage-docker/blob/master/Changelog.md
# for a list of version numbers.
FROM phusion/baseimage:0.9.16

MAINTAINER devops@pythian.com

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

RUN apt-get update \
 && apt-get install -y -q --no-install-recommends \
    nginx-extras \
    wget \
    curl \
 && apt-get clean \
 && rm -r /var/lib/apt/lists/*

# Remove default site
RUN rm /etc/nginx/sites-enabled/default

# Add our dashboard config to nginx
COPY dashboard.conf /etc/nginx/sites-enabled/dashboard.conf

# Make nginx start up
COPY runit.nginx.sh /etc/service/nginx/run

# Install confd
RUN curl -sqL https://github.com/kelseyhightower/confd/releases/download/v0.9.0/confd-0.9.0-linux-amd64 -o /confd && chmod +x /confd

COPY nginx.toml /etc/confd/conf.d/nginx.toml
COPY dashboard.tmpl /etc/confd/templates/dashboard.tmpl

RUN mkdir -p /var/www/dashboard
WORKDIR /var/www/dashboard

# Make confd start up
# COPY runit.confd.sh /etc/service/confd/run

# ENV ETCD_HOST=etcd \
#     ETCD_PORT 4001

EXPOSE 8080
